### ISSUE TITLE
Clamping?

### ISSUE THREAD

**Issue by agittm** [EmreBeratKR/IdleCash#1]
How to clamp between two values like Mathf.Clamp?
Maybe something like
```c#
IdleCash myCash = new IdleCash(100f, "a");
IdleCash limitCash = new IdleCash(1f, "b");
myCash = IdleCash.Clamp(myCash + 1_000_000_000, IdleCash.Zero, limitCash);
``` 

Anyway, thanks for creating this awesome essential asset for idle games!

**Comment by EmreBeratKR** [comment]
Hello, thanks for using my asset. Glad you liked it.

I really appreciate your suggestion.
I have added IdleCash.Clamp static method and can be used in the same way with your example usage.
I have also add the test to the test scene. You may test the method there.

This is the related update commit: c2efc8e42cc8e9a14a02701f14991732943ce005


I will close the issue now. You can reopen a new issue if you face an issue with this update.
Hope this update will help you.
